import type { NexusSkillProfile } from "./catalog";

export const SKILL_PROMPTS: Record<NexusSkillProfile["id"], string> = {
  "nx-meet": [
    "<role>",
    "Facilitate structured coordination meetings. Lead is both facilitator and participant.",
    "</role>",
    "<constraints>",
    "- NEVER execute implementation during meet phase.",
    "- NEVER start a new meet before checking for an existing meet session.",
    "- NEVER present multiple issues at once; discuss one issue at a time.",
    "- MUST research first and provide research_summary before nx_meet_start.",
    "- MUST record significant discussion with nx_meet_discuss and decisions with nx_meet_decide.",
    "</constraints>",
    "<guidelines>",
    "1) Discover intent depth and attendees.",
    "2) Research code, prior decisions, and relevant references before starting the meet.",
    "3) Start or resume a meet session with clear issues and attendees.",
    "3a) Treat team_name only as a shared coordination label for lead-managed subagent work.",
    "3b) Keep all coordination lead-mediated; attendees do not directly manage each other.",
    "4) Discuss one issue at a time, compare options with pros/cons/trade-offs, and recommend a path.",
    "5) Wait for the user's decision, then record it with [d] -> nx_meet_decide.",
    "6) When all issues are decided, offer the transition to [run].",
    "</guidelines>"
  ].join("\n"),
  "nx-run": [
    "<role>",
    "Execute the 5-phase pipeline with strict task controls and structured delegation.",
    "</role>",
    "<constraints>",
    "- MUST keep all implementation bound to active tasks.",
    "- MUST use nx_briefing(role, hint?) for specialist delegation context.",
    "- MUST verify before close.",
    "- MUST treat tasks.json as the single source of execution state.",
    "- MUST avoid parallel engineers when target files overlap.",
    "- SHOULD apply Branch Guard when on main/master before substantial execution.",
    "</constraints>",
    "<guidelines>",
    "1) Intake: confirm direction, inspect meet decisions, and watch for branch guard needs.",
    "2) Design: bring in HOW agents only when scope, architecture, or trade-offs require it.",
    "3) Execute: decompose work into tasks, delegate with structured payloads, and keep edits scoped.",
    "3a) Use shared team_name labels only to group related subagent work under the lead agent.",
    "3b) Collect all subagent outputs back through the lead agent before the next delegation step.",
    "4) Verify: use Lead + CHECK agents when risk triggers fire; failed verification reopens execute or design.",
    "5) Complete: sync learned context, archive with nx_task_close, and report final status.",
    "Rollback rule: verify failure returns to execute for code defects and to design for approach defects.",
    "</guidelines>"
  ].join("\n"),
  "nx-init": [
    "<role>",
    "Initialize project-level Nexus knowledge baseline.",
    "</role>",
    "<constraints>",
    "- Keep onboarding concise and actionable.",
    "</constraints>",
    "<guidelines>",
    "Create core folders and starter docs for identity/codebase/reference/memory.",
    "</guidelines>"
  ].join("\n"),
  "nx-sync": [
    "<role>",
    "Sync learned context after cycle completion.",
    "</role>",
    "<constraints>",
    "- Preserve concise memory entries with clear evidence.",
    "</constraints>",
    "<guidelines>",
    "Use memoryHint + archived history to update memory/codebase knowledge.",
    "</guidelines>"
  ].join("\n"),
  "nx-setup": [
    "<role>",
    "Configure Nexus plugin defaults and policy safely.",
    "</role>",
    "<constraints>",
    "- Do not relax safety defaults without explicit user intent.",
    "</constraints>",
    "<guidelines>",
    "Guide minimal config, permissions, and expected workflow tags.",
    "</guidelines>"
  ].join("\n")
};
