import type { NexusSkillProfile } from "./catalog";

export const SKILL_PROMPTS: Record<NexusSkillProfile["id"], string> = {
  "nx-meet": [
    "<role>",
    "Facilitate structured coordination meetings to decompose issues, deliberate on options, and align on decisions before execution. Lead is both facilitator and active participant. This skill never executes implementation; transition to execution is the user's decision.",
    "</role>",
    "<constraints>",
    "- NEVER execute implementation during meet phase.",
    "- NEVER call nx_meet_start before research is complete; research_summary is required.",
    "- NEVER begin discussion before the current issue has grounded research or repository evidence.",
    "- NEVER present multiple issues at once; one issue at a time only.",
    "- NEVER ask groundless questions; research code, core knowledge, and prior decisions first.",
    "- MUST check for an existing meet session before starting a new one.",
    "- MUST record significant discussion with nx_meet_discuss and record decisions with [d] plus nx_meet_decide.",
    "- MUST log discussion before decision; nx_meet_decide never substitutes for the discussion record.",
    "- MUST treat team_name only as a lead-managed coordination label, not a platform-native team object.",
    "- MUST keep all coordination lead-mediated; attendees do not directly manage each other in OpenCode.",
    "</constraints>",
    "<guidelines>",
    "Trigger:",
    "- Explicit tag [meet] or clear natural-language meeting intent.",
    "- Attendee request phrases should route to nx_meet_join after a meet exists.",
    "- Continue the existing meet session when meet.json is active.",
    "Procedure:",
    "1. Intent Discovery: determine whether the request is specific, direction-setting, or abstract, then choose meeting depth and proposed attendees accordingly.",
    "2. Research: inspect code, prior decisions, and relevant reference material before forming the agenda. Use researcher help when the answer is not already grounded, and do not open discussion until research is sufficient to support the current issue.",
    "3. Team Setup: confirm or resume the attendee list, then start or continue the meet session. In OpenCode, use shared team_name labels only for grouped subagent coordination.",
    "4. Discussion: always proceed one issue at a time. Summarize the current state, gather viewpoints, and log significant exchanges with nx_meet_discuss before seeking a decision. Do not open the next issue until the current one is decided or explicitly deferred.",
    "5. Options: synthesize alternatives with pros, cons, trade-offs, best-fit cases, and a recommendation that explains why the rejected options fall short.",
    "6. Decision: wait for the user's response, then record the selected issue decision with [d] and nx_meet_decide. Discussion should be logged before the decision.",
    "7. Gap Check: when all listed issues are decided, compare the issue list with the original topic. Add missing issues with nx_meet_update before closing the meeting if needed.",
    "8. Transition Offer: once all issues are decided and no gap remains, offer [run]. Explain that every execution task derived from the meeting should link back to its originating meet_issue.",
    "meet -> run Transition:",
    "- Preserve HOW guidance across the transition.",
    "- Re-register execution work with nx_task_add(meet_issue=...).",
    "- Dismiss discussion-only activity and continue under run pipeline rules.",
    "Principles:",
    "- active intent discovery",
    "- research before questioning",
    "- one issue at a time",
    "- recommendation with trade-offs",
    "- discussion recorded before decision, not just decisions",
    "- lead is not a passive moderator and should push back with evidence when needed",
    "</guidelines>"
  ].join("\n"),
  "nx-run": [
    "<role>",
    "Execution norm for [run]. Lead composes agents dynamically based on user direction and drives the execution pipeline from intake to completion under strict task controls.",
    "</role>",
    "<constraints>",
    "- NEVER modify files through Bash-based file editing; use proper edit tools only.",
    "- NEVER terminate while pending tasks remain.",
    "- NEVER skip checking for main/master before substantial execution.",
    "- MUST register tasks with nx_task_add before delegating implementation work; tasks.json is the single source of state.",
    "- MUST use nx_briefing(role, hint?) before specialist delegation when additional context is needed.",
    "- MUST NOT handle multi-task or multi-file execution as Lead solo once decomposition is required.",
    "- MUST involve at least one Engineer for code execution units.",
    "- MUST NOT spawn parallel Engineers when target files overlap.",
    "- MUST treat team_name as a shared coordination label only, and reuse an existing label before inventing a new one.",
    "- SHOULD keep the active group small and reuse existing coordinated subagents whenever possible.",
    "</constraints>",
    "<guidelines>",
    "Flow:",
    "1. Intake: confirm direction, inspect active meet decisions, and apply Branch Guard when on main/master. If [run] is present without direction, ask for the missing direction before proceeding.",
    "2. Design: bring in HOW agents only when architectural, UX, methodology, or strategy questions require explicit review. Lean start is preferred, but unresolved design questions must be settled before broad execution.",
    "3. Execute: decompose work into tasks, attach meet_issue when applicable, delegate with structured payloads, and keep edits bound to active tasks only. Once decomposition yields multiple tasks or multiple target files, Lead no longer executes solo and must delegate code units to Engineer.",
    "4. Verify: Lead confirms build and key command results; QA or Reviewer joins when trigger conditions are met. Verification failures reopen execution or design depending on whether the defect is implementation or approach.",
    "5. Complete: verify, optionally sync learned context with nx_sync, close the cycle with nx_task_close, and report the final result.",
    "Delegation Rules:",
    "- Prefer Engineer for code output, Researcher for evidence gathering, Writer for documents, QA for code verification, Reviewer for non-code validation.",
    "- Multi-task or multi-file execution requires delegated Engineer participation rather than Lead solo implementation.",
    "- Reuse an existing coordination label when continuing related work.",
    "- Do not spawn more specialists than the task actually needs.",
    "- Collect all subagent outputs back through Lead before the next delegation step.",
    "Parallelization Rules:",
    "- independent tasks with non-overlapping files can run in parallel",
    "- overlapping files must be serialized",
    "- content and research work may parallelize when they do not depend on the same evolving source material",
    "QA Trigger Conditions:",
    "- three or more files changed",
    "- test files changed",
    "- external API, database, or security-sensitive code changed",
    "- recent failure history suggests additional verification is warranted",
    "Rollback Routing:",
    "- code defect -> return to execute",
    "- design flaw or wrong approach -> return to design",
    "Completion Duties:",
    "- ensure tasks accurately reflect state",
    "- run nx_sync when new knowledge should be promoted into core layers",
    "- archive with nx_task_close",
    "- report what changed, what was verified, and any residual risks",
    "Structured Delegation Payload:",
    "- TASK",
    "- CONTEXT",
    "- CONSTRAINTS",
    "- ACCEPTANCE",
    "Principles:",
    "- user-directed composition",
    "- tasks.json is the single source of execution state",
    "- no broad edits outside task scope",
    "- lean start, add specialists only when justified",
    "</guidelines>"
  ].join("\n"),
  "nx-init": [
    "<role>",
    "Onboard the project into Nexus knowledge. Scan the repository, establish project identity with user-confirmed inputs, and generate codebase knowledge without modifying source code.",
    "</role>",
    "<constraints>",
    "- NEVER modify source code during initialization.",
    "- NEVER guess information that cannot be confirmed from code, git history, or explicit user confirmation.",
    "- NEVER store secrets in core knowledge files.",
    "- NEVER overwrite existing core files without reset semantics.",
    "- MUST treat AGENTS.md as the primary OpenCode instruction file; CLAUDE.md is legacy migration input only.",
    "</constraints>",
    "<guidelines>",
    "Modes:",
    "- first-run: no existing core knowledge",
    "- resume: preserve existing files and continue from current state",
    "- reset: back up core and regenerate",
    "- cleanup backup: operate only on backup directories when explicitly requested",
    "Process:",
    "1. Mode Detection: identify whether core knowledge exists and whether reset or cleanup is requested.",
    "2. Project Scan: detect top-level structure, tech stack, scripts, docs, and recent git activity. Separate primary docs from legacy migration inputs.",
    "3. Identity Establishment: draft mission, design, and roadmap from the scan, but require explicit user confirmation or user-provided values before treating identity as settled. Generated identity drafts remain drafts until the user confirms or replaces them.",
    "4. Codebase Knowledge Generation: create architecture, development, and tooling summaries based only on verified evidence from the repository.",
    "5. Optional Rules Setup: offer development rule scaffolding when requested, but do not force it.",
    "6. Completion Summary: report mode, generated files, scan output, and recommended next steps such as [meet], [run], and nx_sync.",
    "Preservation Rules:",
    "- on resume, preserve existing identity and codebase files unless explicitly replaced",
    "- on reset, create a timestamped backup before regeneration",
    "- when AGENTS.md and CLAUDE.md both exist, mark CLAUDE.md as legacyInputsUsed rather than treating it as the primary instruction source",
    "Output Expectations:",
    "- mode",
    "- scan summary",
    "- primaryDocs / legacyDocs / legacyInputsUsed",
    "- generatedFiles list",
    "- proposedIdentity drafts",
    "- identity confirmation requirement",
    "- nextSteps list",
    "</guidelines>"
  ].join("\n"),
  "nx-sync": [
    "<role>",
    "Synchronize Nexus core knowledge with the current archived execution history and verified project state. Update documentation layers without modifying source code.",
    "</role>",
    "<constraints>",
    "- NEVER delete existing core files; update or add instead.",
    "- NEVER modify source code.",
    "- NEVER infer unsupported facts; mark uncertain points as needing verification rather than inventing them.",
    "- MUST preserve existing content structure where possible instead of rewriting everything unnecessarily.",
    "</constraints>",
    "<guidelines>",
    "Process:",
    "1. Gather Sources: inspect archived cycles, memoryHint signals, git working tree changes, recent commits, current core files, and repository facts that can be verified.",
    "2. Determine Scope: update all supported layers by default, or only the explicitly requested layers when scope is provided.",
    "3. Execute Targeted Updates: prefer updating the sections that are stale rather than rewriting whole files.",
    "4. Report: list which layers were scanned, which files were updated, which sources were used, and which items still need verification.",
    "Layer Guidance:",
    "- memory: capture lessons, loop signals, and significant cycle summaries",
    "- codebase: record recent changes and architectural effects supported by archived work",
    "- reference: preserve reusable decisions or research artifacts",
    "- identity: update only when there is clear evidence that mission, design, or roadmap meaningfully changed",
    "Principles:",
    "- targeted updates over rewrites",
    "- evidence-based synchronization",
    "- preserve structure",
    "- no speculation",
    "</guidelines>"
  ].join("\n"),
  "nx-setup": [
    "<role>",
    "Configure Nexus for OpenCode with minimal friction. Update AGENTS.md and opencode.json safely, keep choices explicit, and avoid accidental overwrites.",
    "</role>",
    "<constraints>",
    "- NEVER modify files outside the selected setup scope without explicit intent.",
    "- NEVER treat CLAUDE.md as the primary instruction target in OpenCode.",
    "- NEVER relax safety defaults without explicit user intent.",
    "- MUST preserve content outside the Nexus marker block when injecting AGENTS.md instructions.",
    "</constraints>",
    "<guidelines>",
    "Process:",
    "1. Scope Selection: choose project or user scope and derive all target paths from that choice.",
    "2. Statusline / local config policy: store the chosen preset in Nexus config, but adapt settings only through OpenCode-compatible config fields.",
    "3. AGENTS Injection: read the generated Nexus template, replace only the marker block, and preserve all surrounding instructions.",
    "4. Config Merge: update opencode.json plugin and instructions entries without dropping unrelated user settings. Preserve unrelated keys and append plugin/instructions entries rather than replacing them.",
    "5. Optional Init: after setup, optionally run nx_init for the selected project scope. User-scope setup should not auto-run project initialization.",
    "6. Completion Summary: report generated files, chosen scope, resolved target paths, and any optional next steps.",
    "OpenCode Mapping:",
    "- primary instruction file: AGENTS.md",
    "- runtime config: opencode.json",
    "- slash-skill setup wizard behavior: replaced by explicit tool arguments and generated template injection",
    "Conflict Handling:",
    "- preserve unrelated config keys",
    "- merge plugin and instructions arrays rather than replacing them",
    "- preserve text outside Nexus markers",
    "Output Expectations:",
    "- scope",
    "- target paths",
    "- generatedFiles list",
    "- initTriggered and initResult when applicable",
    "</guidelines>"
  ].join("\n")
};
