// Auto-generated by build-agents.ts — do not edit

import { architect } from "./agents/architect.js";
import { designer } from "./agents/designer.js";
import { engineer } from "./agents/engineer.js";
import { lead } from "./agents/lead.js";
import { postdoc } from "./agents/postdoc.js";
import { researcher } from "./agents/researcher.js";
import { reviewer } from "./agents/reviewer.js";
import { strategist } from "./agents/strategist.js";
import { tester } from "./agents/tester.js";
import { writer } from "./agents/writer.js";

export const agents = [
  architect,
  designer,
  engineer,
  lead,
  postdoc,
  researcher,
  reviewer,
  strategist,
  tester,
  writer,
];
